import Foundation
import SwiftUI

enum ToolMockData {
    static let tools: [ToolItem] = [
        ToolItem(
            id: "t1", name: "Perceuse Bosch Pro", description: "Perceuse à percussion sans fil 18V avec 2 batteries lithium-ion. Couple max 82 Nm. Idéale pour perçage béton, bois et métal. Mandrin auto-serrant 13mm. Coffret de transport inclus avec jeu de forets.",
            category: .outilsManuels, status: .disponible,
            ownerName: "Laurent Dupont", ownerVerified: true, rating: 4.8, reviewCount: 156,
            brand: "Bosch", model: "GSB 18V-85 C", year: 2023, condition: .bonEtat, skillLevel: .debutant,
            weight: "2.1 kg", dimensions: "20 × 8 × 25 cm",
            consumablesIncluded: true, consumablesDetail: "Jeu de 10 forets béton/bois/métal",
            hasManual: true,
            pricePerHour: "8 €", pricePerDay: "35 €", pricePerWeek: "180 €", pricePerMonth: "450 €",
            deposit: "350 €", icon: "wrench.and.screwdriver.fill",
            gallery: ["wrench.and.screwdriver.fill", "battery.100.bolt", "hammer.fill", "ruler.fill"],
            features: ["Sans fil", "18V", "2 batteries", "Coffret"],
            occupiedUntil: nil, cleaningMinutes: 15, nextAvailable: nil,
            latitude: 48.8566, longitude: 2.3522, address: "Paris 1er, Rue de Rivoli",
            accessMethod: .mainPropre, deliveryAvailable: false, deliveryPrice: nil, insuranceRate: 0.05
        ),
        ToolItem(
            id: "t2", name: "Meuleuse Makita 230mm", description: "Meuleuse d'angle professionnelle 2200W. Disque 230mm pour coupe et meulage intensifs. Protection anti-redémarrage, poignée anti-vibration. Parfaite pour chantier.",
            category: .outilsManuels, status: .occupe,
            ownerName: "Philippe Martin", ownerVerified: true, rating: 4.6, reviewCount: 89,
            brand: "Makita", model: "GA9060", year: 2022, condition: .usureNormale, skillLevel: .intermediaire,
            weight: "5.5 kg", dimensions: "50 × 18 × 15 cm",
            consumablesIncluded: true, consumablesDetail: "3 disques de coupe + 2 disques à lamelles",
            hasManual: true,
            pricePerHour: "10 €", pricePerDay: "45 €", pricePerWeek: "220 €", pricePerMonth: "550 €",
            deposit: "450 €", icon: "circle.dotted.circle",
            gallery: ["circle.dotted.circle", "bolt.fill", "shield.checkered", "hand.raised.fill"],
            features: ["2200W", "230mm", "Anti-vibration", "Pro"],
            occupiedUntil: Date().addingTimeInterval(86400 * 2), cleaningMinutes: 20, nextAvailable: "18 Avr",
            latitude: 48.8738, longitude: 2.2950, address: "Paris 16ème, Rue de la Pompe",
            accessMethod: .mainPropre, deliveryAvailable: false, deliveryPrice: nil, insuranceRate: 0.05
        ),
        ToolItem(
            id: "t3", name: "Générateur Honda 6.5kVA", description: "Groupe électrogène silencieux avec moteur Honda GX390. Démarrage électrique, autonomie 8h à 75% de charge. Prises 220V et 380V. Idéal chantier et événementiel.",
            category: .machines, status: .disponible,
            ownerName: "Nicolas Lefèvre", ownerVerified: true, rating: 4.9, reviewCount: 203,
            brand: "Honda", model: "EU65is", year: 2023, condition: .neuf, skillLevel: .intermediaire,
            weight: "88 kg", dimensions: "73 × 56 × 58 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: true,
            pricePerHour: "25 €", pricePerDay: "120 €", pricePerWeek: "600 €", pricePerMonth: "1 800 €",
            deposit: "1 500 €", icon: "bolt.square.fill",
            gallery: ["bolt.square.fill", "powerplug.fill", "gauge.open.with.lines.needle.67percent", "fuelpump.fill"],
            features: ["6.5kVA", "Silencieux", "Honda", "8h autonomie"],
            occupiedUntil: nil, cleaningMinutes: 30, nextAvailable: nil,
            latitude: 48.8867, longitude: 2.3431, address: "Paris 18ème, Rue Ordener",
            accessMethod: .livraison, deliveryAvailable: true, deliveryPrice: "80 €", insuranceRate: 0.08
        ),
        ToolItem(
            id: "t4", name: "Compresseur Atlas Copco", description: "Compresseur à vis rotatif 7.5 bar, débit 1000 l/min. Silencieux, sur roues. Alimentation 380V. Pour peinture, sablage, outils pneumatiques.",
            category: .machines, status: .nettoyage,
            ownerName: "Julien Moreau", ownerVerified: true, rating: 4.5, reviewCount: 67,
            brand: "Atlas Copco", model: "GA 7+", year: 2021, condition: .bonEtat, skillLevel: .professionnel,
            weight: "210 kg", dimensions: "120 × 60 × 90 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: true,
            pricePerHour: nil, pricePerDay: "150 €", pricePerWeek: "750 €", pricePerMonth: "2 200 €",
            deposit: "2 500 €", icon: "wind",
            gallery: ["wind", "gauge.open.with.lines.needle.33percent", "circle.grid.3x3.fill", "waveform.path"],
            features: ["7.5 bar", "1000 l/min", "Sur roues", "380V"],
            occupiedUntil: nil, cleaningMinutes: 45, nextAvailable: nil,
            latitude: 48.9002, longitude: 2.3834, address: "Saint-Denis, Zone Industrielle",
            accessMethod: .livraison, deliveryAvailable: true, deliveryPrice: "120 €", insuranceRate: 0.08
        ),
        ToolItem(
            id: "t5", name: "Pelle hydraulique CAT 320", description: "Pelle sur chenilles 20 tonnes. Profondeur de fouille 6.7m. Cabine climatisée avec caméra de recul. Godet standard 1.2m³ inclus. Opérateur disponible en option.",
            category: .enginsBTP, status: .disponible,
            ownerName: "Éric Blanchard", ownerVerified: true, rating: 4.7, reviewCount: 34,
            brand: "Caterpillar", model: "320 GC", year: 2022, condition: .bonEtat, skillLevel: .professionnel,
            weight: "20 500 kg", dimensions: "960 × 290 × 305 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: true,
            pricePerHour: "180 €", pricePerDay: "950 €", pricePerWeek: "4 500 €", pricePerMonth: "14 000 €",
            deposit: "10 000 €", icon: "square.stack.3d.up.fill",
            gallery: ["square.stack.3d.up.fill", "arrow.up.arrow.down", "thermometer.medium", "camera.metering.center.weighted"],
            features: ["20T", "Climatisée", "Caméra recul", "Godet 1.2m³"],
            occupiedUntil: nil, cleaningMinutes: 60, nextAvailable: nil,
            latitude: 48.9300, longitude: 2.3600, address: "Aubervilliers, Zone Chantier Nord",
            accessMethod: .livraison, deliveryAvailable: true, deliveryPrice: "650 €", insuranceRate: 0.12
        ),
        ToolItem(
            id: "t6", name: "Nacelle élévatrice 12m", description: "Nacelle articulée diesel, hauteur de travail 12m. Capacité 230 kg. 4 roues motrices, adaptée tous terrains. Commandes au panier et au sol.",
            category: .enginsBTP, status: .libreLe,
            ownerName: "Thomas Bernard", ownerVerified: true, rating: 4.4, reviewCount: 21,
            brand: "JLG", model: "340AJ", year: 2021, condition: .usureNormale, skillLevel: .professionnel,
            weight: "5 400 kg", dimensions: "580 × 180 × 220 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: true,
            pricePerHour: nil, pricePerDay: "550 €", pricePerWeek: "2 800 €", pricePerMonth: "8 000 €",
            deposit: "5 000 €", icon: "arrow.up.to.line",
            gallery: ["arrow.up.to.line", "arrow.up.left.and.arrow.down.right", "figure.stand", "exclamationmark.triangle.fill"],
            features: ["12m", "Diesel", "4×4", "Articulée"],
            occupiedUntil: Date().addingTimeInterval(86400 * 5), cleaningMinutes: 45, nextAvailable: "20 Avr",
            latitude: 48.8200, longitude: 2.3300, address: "Ivry-sur-Seine, Zone Industrielle",
            accessMethod: .livraison, deliveryAvailable: true, deliveryPrice: "450 €", insuranceRate: 0.10
        ),
        ToolItem(
            id: "t7", name: "Tracteur John Deere 5075E", description: "Tracteur utilitaire 75 CV avec prise de force. Cabine ouverte, direction assistée. Compatible avec tous les outils attelés. Entretien récent.",
            category: .agricole, status: .disponible,
            ownerName: "Pierre Gauthier", ownerVerified: true, rating: 4.8, reviewCount: 45,
            brand: "John Deere", model: "5075E", year: 2022, condition: .bonEtat, skillLevel: .intermediaire,
            weight: "2 800 kg", dimensions: "380 × 185 × 260 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: true,
            pricePerHour: "65 €", pricePerDay: "350 €", pricePerWeek: "1 800 €", pricePerMonth: "5 200 €",
            deposit: "3 000 €", icon: "leaf.fill",
            gallery: ["leaf.fill", "gearshape.2.fill", "fuelpump.fill", "sun.max.fill"],
            features: ["75 CV", "Prise de force", "Direction assistée", "Diesel"],
            occupiedUntil: nil, cleaningMinutes: 30, nextAvailable: nil,
            latitude: 48.5000, longitude: 2.6000, address: "Melun, Zone Agricole",
            accessMethod: .mainPropre, deliveryAvailable: true, deliveryPrice: "250 €", insuranceRate: 0.10
        ),
        ToolItem(
            id: "t8", name: "Sono complète 2000W", description: "Système son professionnel : 2 enceintes actives 1000W, 1 caisson de basse 18\", table de mixage 12 canaux, 2 micros sans fil. Câblage complet inclus.",
            category: .evenementiel, status: .disponible,
            ownerName: "Sophie Lemaire", ownerVerified: true, rating: 4.9, reviewCount: 178,
            brand: "QSC / Yamaha", model: "K12.2 + MG12XU", year: 2023, condition: .neuf, skillLevel: .intermediaire,
            weight: "85 kg (total)", dimensions: "Variable",
            consumablesIncluded: true, consumablesDetail: "Câbles XLR, adaptateurs, rallonges électriques",
            hasManual: true,
            pricePerHour: "50 €", pricePerDay: "250 €", pricePerWeek: "1 200 €", pricePerMonth: "3 500 €",
            deposit: "2 000 €", icon: "speaker.wave.3.fill",
            gallery: ["speaker.wave.3.fill", "music.mic", "slider.horizontal.3", "cable.connector"],
            features: ["2000W", "2 micros sans fil", "Table mixage", "Caisson 18\""],
            occupiedUntil: nil, cleaningMinutes: 30, nextAvailable: nil,
            latitude: 48.8450, longitude: 2.3600, address: "Paris 11ème, Rue Oberkampf",
            accessMethod: .mainPropre, deliveryAvailable: true, deliveryPrice: "80 €", insuranceRate: 0.06
        ),
        ToolItem(
            id: "t9", name: "Kit tente 6×12m + éclairage", description: "Tente chapiteau 6×12m en PVC blanc. Structure aluminium démontable. Éclairage LED intégré (guirlandes + spots). Sol en dalles PVC clipsables. Installation comprise.",
            category: .evenementiel, status: .occupe,
            ownerName: "Marc Fontaine", ownerVerified: true, rating: 4.7, reviewCount: 92,
            brand: "Tent Pro", model: "Majestic 6×12", year: 2023, condition: .neuf, skillLevel: .debutant,
            weight: "320 kg (total)", dimensions: "600 × 1200 × 350 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: false,
            pricePerHour: nil, pricePerDay: "350 €", pricePerWeek: "1 800 €", pricePerMonth: "5 000 €",
            deposit: "2 500 €", icon: "tent.fill",
            gallery: ["tent.fill", "light.max", "square.grid.3x3.middle.filled", "party.popper.fill"],
            features: ["6×12m", "LED intégré", "PVC blanc", "Installation"],
            occupiedUntil: Date().addingTimeInterval(86400 * 3), cleaningMinutes: 120, nextAvailable: "19 Avr",
            latitude: 48.8700, longitude: 2.3200, address: "Paris 17ème, Espace Événements",
            accessMethod: .livraison, deliveryAvailable: true, deliveryPrice: "180 €", insuranceRate: 0.06
        ),
        ToolItem(
            id: "t10", name: "Moteur hors-bord Yamaha 40CV", description: "Moteur hors-bord 4 temps 40 CV. Démarrage électrique, trim & tilt. Fiable et économique. Compatible annexes et semi-rigides. Hélice incluse.",
            category: .nautique, status: .disponible,
            ownerName: "Antoine Leroy", ownerVerified: true, rating: 4.6, reviewCount: 38,
            brand: "Yamaha", model: "F40FETL", year: 2022, condition: .bonEtat, skillLevel: .intermediaire,
            weight: "86 kg", dimensions: "68 × 38 × 120 cm",
            consumablesIncluded: false, consumablesDetail: nil,
            hasManual: true,
            pricePerHour: "40 €", pricePerDay: "200 €", pricePerWeek: "1 000 €", pricePerMonth: "3 000 €",
            deposit: "2 500 €", icon: "water.waves",
            gallery: ["water.waves", "engine.combustion.fill", "fuelpump.fill", "sailboat.fill"],
            features: ["40 CV", "4 temps", "Électrique", "Trim & tilt"],
            occupiedUntil: nil, cleaningMinutes: 45, nextAvailable: nil,
            latitude: 43.2965, longitude: 5.3698, address: "Vieux-Port, Marseille",
            accessMethod: .mainPropre, deliveryAvailable: false, deliveryPrice: nil, insuranceRate: 0.10
        ),
        ToolItem(
            id: "t11", name: "Rotofaucheuse Kuhn 2.8m", description: "Rotofaucheuse portée arrière 2.8m de large. 24 couteaux. Compatible tracteurs 60-100 CV. Coupe rase et propre. Idéale pour prairies et jachères.",
            category: .agricole, status: .disponible,
            ownerName: "Maxime Perrin", ownerVerified: false, rating: 4.3, reviewCount: 18,
            brand: "Kuhn", model: "GMD 2811", year: 2021, condition: .usureNormale, skillLevel: .intermediaire,
            weight: "580 kg", dimensions: "280 × 190 × 110 cm",
            consumablesIncluded: true, consumablesDetail: "Jeu de couteaux de rechange (24 pcs)",
            hasManual: true,
            pricePerHour: nil, pricePerDay: "180 €", pricePerWeek: "900 €", pricePerMonth: "2 600 €",
            deposit: "2 000 €", icon: "leaf.arrow.circlepath",
            gallery: ["leaf.arrow.circlepath", "scissors", "sun.max.fill", "tractor"],
            features: ["2.8m", "24 couteaux", "60-100 CV", "Portée"],
            occupiedUntil: nil, cleaningMinutes: 30, nextAvailable: nil,
            latitude: 48.5100, longitude: 2.5800, address: "Melun, Piste Agricole",
            accessMethod: .mainPropre, deliveryAvailable: true, deliveryPrice: "150 €", insuranceRate: 0.08
        ),
        ToolItem(
            id: "t12", name: "Visseuse DeWalt 18V", description: "Visseuse à chocs compacte 18V XR Brushless. Couple max 205 Nm. 3 vitesses. Éclairage LED intégré. Livrée avec 2 batteries 5Ah et chargeur rapide.",
            category: .outilsManuels, status: .disponible,
            ownerName: "François Mercier", ownerVerified: true, rating: 4.7, reviewCount: 98,
            brand: "DeWalt", model: "DCF887P2", year: 2023, condition: .neuf, skillLevel: .debutant,
            weight: "1.1 kg", dimensions: "14 × 5 × 23 cm",
            consumablesIncluded: true, consumablesDetail: "Embouts tournevis assortis (25 pcs)",
            hasManual: true,
            pricePerHour: "5 €", pricePerDay: "25 €", pricePerWeek: "120 €", pricePerMonth: "300 €",
            deposit: "250 €", icon: "screwdriver.fill",
            gallery: ["screwdriver.fill", "battery.100.bolt", "lightbulb.led.fill", "wrench.adjustable.fill"],
            features: ["18V", "Brushless", "3 vitesses", "LED"],
            occupiedUntil: nil, cleaningMinutes: 10, nextAvailable: nil,
            latitude: 48.8530, longitude: 2.3499, address: "Paris 5ème, Rue Mouffetard",
            accessMethod: .qrAccess, deliveryAvailable: false, deliveryPrice: nil, insuranceRate: 0.05
        ),
    ]

    static let ownerTools: [OwnerTool] = [
        OwnerTool(
            id: "ot1",
            tool: tools[0],
            todayRevenue: "105 €",
            weekRevenue: "560 €",
            monthRevenue: "2 250 €",
            totalRevenue: "12 400 €",
            reservationCount: 67,
            bookings: []
        ),
        OwnerTool(
            id: "ot2",
            tool: tools[2],
            todayRevenue: "240 €",
            weekRevenue: "1 320 €",
            monthRevenue: "4 800 €",
            totalRevenue: "28 600 €",
            reservationCount: 134,
            bookings: []
        ),
        OwnerTool(
            id: "ot3",
            tool: tools[7],
            todayRevenue: "250 €",
            weekRevenue: "1 000 €",
            monthRevenue: "4 200 €",
            totalRevenue: "21 500 €",
            reservationCount: 92,
            bookings: []
        ),
    ]

    static let toolRevenue: [ToolRevenueData] = [
        ToolRevenueData(id: "tr1", toolName: "Perceuse Bosch Pro", icon: "wrench.and.screwdriver.fill", revenue: "2 250 €", percentage: 0.25),
        ToolRevenueData(id: "tr2", toolName: "Générateur Honda", icon: "bolt.square.fill", revenue: "4 800 €", percentage: 0.50),
        ToolRevenueData(id: "tr3", toolName: "Sono complète", icon: "speaker.wave.3.fill", revenue: "4 200 €", percentage: 0.43),
    ]

    static let weekEvents: [WeekEvent] = [
        WeekEvent(id: "te1", title: "Perceuse → Lucas M.", day: "Lun", timeRange: "08:00 – 18:00", color: .green),
        WeekEvent(id: "te2", title: "Sono → Événement Versailles", day: "Mar", timeRange: "Toute la journée", color: .green),
        WeekEvent(id: "te3", title: "Nettoyage Générateur", day: "Mer", timeRange: "08:00 – 10:00", color: .orange),
        WeekEvent(id: "te4", title: "Générateur → Chantier Aubervilliers", day: "Jeu", timeRange: "07:00 – 19:00", color: .green),
        WeekEvent(id: "te5", title: "Libre", day: "Ven", timeRange: "Toute la journée", color: .blue),
        WeekEvent(id: "te6", title: "Sono → Mariage Fontainebleau", day: "Sam", timeRange: "10:00 – 23:00", color: .green),
        WeekEvent(id: "te7", title: "Libre", day: "Dim", timeRange: "Toute la journée", color: .blue),
    ]
}
